[general]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# decorations = "buttonless"
decorations = "full"
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 25
y = 20

[font]
size = 13.0
# normal = { family = "D2CodingLigature Nerd Font Mono", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMonoHangul Nerd Font Mono", style = "Regular" }

# ── 사용자 키 바인딩 ────────────────────────────────────────
# Alacritty 0.13+ TOML 포맷
[[keyboard.bindings]]         # ⌥← : backward-word (Esc b)
key  = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]         # ⌥→ : forward-word (Esc f)
key  = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]         # ⌘← : beginning-of-line (Ctrl-A)
key  = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]         # ⌘→ : end-of-line (Ctrl-E)
key  = "Right"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]         # ⌥⌫ : delete-previous-word (Esc d)
key  = "Back"
mods = "Command"
chars = "\u0017"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
